config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates_numericality_of :age, :allow_nil => true, :greater_than_or_equal_to => 0
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, except: [:index, :new, :create]
  
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end
  
  def new
    @kitten = Kitten.new
  end
  
  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten successfully created!"
      redirect_to root_url
    else
      flash.now[:danger] = "Kitten was not created!"
      render 'new'
    end
  end
  
  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end
  
  def edit
  end
  
  def update
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten successfully updated!"
      redirect_to @kitten
    else
      render 'edit'
    end
  end
  
  def destroy
    @kitten.destroy
    flash[:success] = "Kitten deleted!"
    redirect_to root_url
  end
  
  private
    
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
    
    def kitten_params
      params.require(:kitten)
            .permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'  %>
   
    <%= f.label :age %>
    <%= f.number_field :age, class: 'form-control'  %>
    
    <%= f.label :cuteness %>
    <%= f.text_field :cuteness, class: 'form-control'  %>
   
    <%= f.label :softness %>
    <%= f.text_field :softness, class: 'form-control'  %><br>
    
    <%= f.submit class: "btn btn-primary" %>
   
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit an Kitten</h1>
<%= render partial: 'form' %>

<%= link_to "Delete", kitten_path(@kitten), method: :delete, 
                    data: { confirm: "You sure?" } %> |

<%= link_to "Back to Kitten", @kitten %>

app/views/kittens/index.html.erb
<h1>Kittens (<%= @kittens.count %>)</h1><br>

 <table class="table table-bordered table-striped" style="width:90%">
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Cuteness</th>
          <th>Softness</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @kittens.each do |kitten| %>
          <tr>
            <td><%= link_to kitten.name, kitten %></td>
            <td><%= kitten.age %></td>
            <td><%= kitten.cuteness %>
            <td><%= kitten.softness %></td> 
            <td><%= link_to "delete", kitten, method: :delete, 
                                 data: { confirm: "You sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<%= link_to "Create a Kitten", new_kitten_path(@kitten) %>

app/views/kittens/new.html.erb
<h1>Create a New Kitten</h1>
<%= render partial: 'form' %><br>

<%= link_to "Back to Kittens", kittens_path %><br>

app/views/kittens/show.html.erb
<h1>Kitten Details</h1>
                    
<table class="table table-bordered table-striped" style="width:90%">
    <tbody>
        <tr>
            <td><b>Name:</b></td>
            <td><%= @kitten.name %></td>
        </tr>
        <tr>
            <td><b>Age:</b></td>
            <td><%= @kitten.age %></td>
        </tr>
        <tr>
            <td><b>Cuteness:</b></td>
            <td><%= @kitten.cuteness %></td>
        </tr>
        <tr>
            <td><b>Softness:</b></td> 
            <td><%= @kitten.softness %></td> 
        </tr>
      </tbody>
    </table>

<%= link_to "Edit", edit_kitten_path %> |
<%= link_to "Delete", kitten_path(@kitten), method: :delete, 
                    data: { confirm: "You sure?" } %><br>
<%= link_to "Back to Kittens", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Note: The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>